version: "3.0"

services:
  db:
    image: mongo
    environment:
      MONGO_INITDB_ROOT_USERNAME: c4shb4ck
      MONGO_INITDB_ROOT_PASSWORD: c4shb4ck
    ports:
      - 27017:27017

  api:
    build:
      context: .
    image: core-api
    ports:
      - 5000:5000
    environment:
      DB_URL: mongodb://c4shb4ck:c4shb4ck@db:27017
    depends_on:
      - db
